### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by schniggie** [devploit/dontgo403#27]
Fails to parse request from Burp:

```
./dontgo403 -r /home/kali/tmp/req 
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
dontgo403/cmd.requester({0xc00016a100, 0x7d}, {0x0?, 0x0?}, {0x0, 0x0}, {0xc00017e400?, 0x10, 0x10}, {0x0, ...}, ...)
	/home/kali/hacktools/web/dontgo403/cmd/requester.go:393 +0x747
dontgo403/cmd.loadFlagsFromRequestFile({0x7fffd2c94fb1?, 0x0?}, 0x0, 0x0?)
	/home/kali/hacktools/web/dontgo403/cmd/api.go:139 +0x305
dontgo403/cmd.glob..func1(0xb7cd00?, {0x860f2b?, 0x2?, 0x2?})
	/home/kali/hacktools/web/dontgo403/cmd/root.go:57 +0x291
github.com/spf13/cobra.(*Command).execute(0xb7cd00, {0xc00011c160, 0x2, 0x2})
	/home/kali/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xb7cd00)
	/home/kali/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/kali/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
dontgo403/cmd.Execute()
	/home/kali/hacktools/web/dontgo403/cmd/root.go:75 +0x25
main.main()
	/home/kali/hacktools/web/dontgo403/main.go:22 +0x17

```

Here is the request:
```
cat ~/tmp/req 
POST /openai/deployments/text-gpt-4-32k/chat/completions?api-version=2023-03-15-preview HTTP/1.1
Host: cdo-eastus-openai.openai.azure.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: cross-site
Te: trailers
Pragma: no-cache
Cache-Control: no-cache
Content-Length: 0
Connection: close
```

**Comment by devploit** [comment]
Hi, it works for me (I just used your request). Can you check if you are using the latest dontgo403 version?

![image](https://github.com/devploit/dontgo403/assets/39808403/ee72eba6-5e99-4242-99cc-00deb196e187)
